#!/bin/bash

if [ "$(uname -m)" = "x86_64" ]; then
  exec arch -arm64e /bin/zsh
fi

# ====================
# Env Variables
# ====================

export PATH="$PATH:/opt/homebrew/bin"
export DOCKER_HOST=unix:///$HOME/.lima/docker/sock/docker.sock

BRER_PREFIX=$(brew config | grep 'HOMEBREW_PREFIX' | cut -d ' ' -f 2)
path=(
  $BRER_PREFIX/opt/coreutils/libexec/gnubin(N-/) # coreutils
  $BRER_PREFIX/opt/ed/libexec/gnubin(N-/) # ed
  $BRER_PREFIX/opt/findutils/libexec/gnubin(N-/) # findutils
  $BRER_PREFIX/opt/gnu-sed/libexec/gnubin(N-/) # sed
  $BRER_PREFIX/opt/gnu-tar/libexec/gnubin(N-/) # tar
  $BRER_PREFIX/opt/grep/libexec/gnubin(N-/) # grep
  ${path}
)
manpath=(
  $BRER_PREFIX/opt/coreutils/libexec/gnuman(N-/) # coreutils
  $BRER_PREFIX/opt/ed/libexec/gnuman(N-/) # ed
  $BRER_PREFIX/opt/findutils/libexec/gnuman(N-/) # findutils
  $BRER_PREFIX/opt/gnu-sed/libexec/gnuman(N-/) # sed
  $BRER_PREFIX/opt/gnu-tar/libexec/gnuman(N-/) # tar
  $BRER_PREFIX/opt/grep/libexec/gnuman(N-/) # grep
  ${manpath}
)

# ====================
# Functions
# ====================
