#!/bin/bash

# ====================
# Environment
# ====================

export CFLAGS=-I/usr/include/openssl
export LDFLAGS=-L/usr/lib

# ====================
# alias
# ====================

alias fd="fd-find"
