[tools]
"npm:@openai/codex" = "0.147.0"
"npm:@earendil-works/pi-coding-agent" = "0.84.2"
"npm:opencode-ai" = "1.18.18"
"npm:@playwright/cli" = "0.1.18"
"npm:@github/copilot" = "1.0.80"
"npm:portless" = "0.15.5"
"npm:@anthropic-ai/sandbox-runtime" = "0.0.49"
"npm:agent-browser" = "0.34.0"
"npm:@anthropic-ai/claude-code" = "2.1.234"
"npm:@kimuson/npm-fw" = "0.0.4"
node = "26.2.0"

[settings]
idiomatic_version_file_enable_tools = ["node"]
