[tools]
"npm:@openai/codex" = "0.146.0"
"npm:@earendil-works/pi-coding-agent" = "0.83.0"
"npm:opencode-ai" = "1.18.11"
"npm:@playwright/cli" = "0.1.17"
"npm:@github/copilot" = "1.0.77"
"npm:portless" = "0.15.5"
"npm:@anthropic-ai/sandbox-runtime" = "0.0.49"
"npm:agent-browser" = "0.33.2"
"npm:@anthropic-ai/claude-code" = "2.1.220"
"npm:@kimuson/npm-fw" = "0.0.4"
node = "26.2.0"

[settings]
idiomatic_version_file_enable_tools = ["node"]
