[package]
edition = "2021"
name = "dotfiles_manager"
version = "0.1.0"

[dependencies]
clap = {version = "4.5.7", features = ["derive"]}
dirs = {version = "5.0.1"}
serde = {version = "1.0", features = ["derive"]}
