# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[username]
disabled = false
format = '[$user]($style) '
show_always = true
style_root = 'black bold'
style_user = 'yellow bold'

[directory]
format = 'at [$path]($style)[$read_only]($read_only_style) '
truncate_to_repo = false
truncation_length = 10000

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
disabled = true
